### ISSUE TITLE
Link instead of copy

### ISSUE THREAD

**Issue by V10lator** [zgfg/BuiltIn-BusyBox#1]
This is just a little feature request: Link the busybox binary instead of copying it and maybe install from that link instead of the magisk path. See my old implementation to get a better understanding of what I mean: https://github.com/V10lator/MagiskBusyBox/blob/master/install.sh#L37-L39

**Comment by zgfg** [comment]
Thanks

Implemented with v1 0.4 - you can check

**Comment by zgfg** [comment]
Implemented with v1 0.4 - you can check
