### ISSUE TITLE
Pixel 7 pro a13 

### ISSUE THREAD

**Issue by bggold** [zgfg/BuiltIn-BusyBox#2]
I am getting a boot loop with v1.0.5.  not sure what information I can get for you.  Let me know.

V1.0.4 works fine.

Thanks

**Comment by Ai686Leo** [comment]
The problem also occurred on my device version 1.05

**Comment by zgfg** [comment]
Hi

@Ai686Leo @bggold 

I'd like to test the fix and release, please perform the following:

1) Download and install the attached BB v1.0.5a-bugfix module
and reboot

Based on results from the other users with similar issues, this version should hopefully work for you :-)

2) Upon rebooting, please use some root explorer like  MiXPlorer and go to:
/data/adb/modules/BuiltIn-BusyBox

find the file post-fs-data.log, copy to your Download folder, zip and provide me back here the log to see results

Please describe also does that v1.0.5.0-bugfix now works fine for you

Thanks

[BuiltIn-BusyBox_v1.0.5a-bugfix.zip](https://github.com/zgfg/BuiltIn-BusyBox/files/11679351/BuiltIn-BusyBox_v1.0.5a-bugfix.zip)

**Comment by bggold** [comment]
Issue fixed with this version.  Here is the log file.
[post-fs-data.zip](https://github.com/zgfg/BuiltIn-BusyBox/files/11679641/post-fs-data.zip)

Thanks for the quick response.

**Comment by zgfg** [comment]
Released:
https://github.com/zgfg/BuiltIn-BusyBox/releases/tag/106
