### ISSUE TITLE
Difference to busybox for Android NDK by osm0sis

### ISSUE THREAD

**Issue by pannal** [zgfg/BuiltIn-BusyBox#3]
Hey,

Thank you for providing this module. This might seem like a stupid question to ask for anyone more involved, but what's the difference between this module and the "default" busybox for Android NDK by osm0sis?

As far as I understand both support systemless installation while the one from osm0sis has a newer busybox underneath.

Thank you!

**Comment by zgfg** [comment]
As the name describes, this module installs for you the BUILT IN BusyBox that comes with Magisk

Use a root explorer (or TWRP) and go to /data/adb/magisk/busybox - that's the one that comes with Magisk and Magisk already took care that it installed the binary for your architecture

But that BusyBox is not 'unpacked' and not 'installed' to /system/(x)bin that you can use it.
Actually you can but you must execute from Terminal emulator like:
/data/adb/magisk/busybox --help
/data/adb/magisk/busybox ascii ---help 
and so.
With this module, you can use that same BB but easily, short and as usually as:
busybox ---help
ascii ---help
etc

Magisk installed it for itself and its own usage

Hence this module zip is eg substantially smaller than NDK module zip, NDK (unzip it) contains various biinaries, and chooses the one for your architecture and installs it

This module also uses less space on the phone than NDK module - it just links (ln -s) to the existing Magisk binary that you have (and cannot avoid it), while NDK has to copy a new binary to your phone

Regarding the BB version - I doubt how much difference does it make for a user, but of course it's up to you

Anyway, when you update Magisk, Magisk will come with the latest BB that was released before the Magisk release (TJW takes care, and he installs binaries from that same NDK 'source"). Hence by updating Magisk, Magisk will automatically update it's BB binary /data/adb/magisk/busybox (usually to the same version as in the NDK module - BB does not update binaries  every day but few times a year or so), and with the next reboot with this module you will also have that newest BB installed

So, answered and closing the ticket

**Comment by zgfg** [comment]
Answered above

**Comment by zgfg** [comment]
PS:

Use Terminal emulator (with su) and ask where the BusyBox was installed by:
which busybox

Then cd to that directory (/system/bin or /system/xbin, depending on your phone and ROM)

and execute
ls -l | grep busyb

It will list you BB and all BB applets and you will see that they all are linked to /data/adb/magisk/busybox binary
